package org.mpilone.vaadin.shared;

import java.util.List;

import com.vaadin.shared.communication.ServerRpc;

/**
 * The remote procedure call interface which allows calls from the client side
 * to the server. For the most part these methods map to the events generated by
 * the Plupload JavaScript component.
 * 
 * @author mpilone
 */
public interface PluploadServerRpc extends ServerRpc {
  public void onUploadFile(PluploadFile file);

  public void onFilesAdded(List<PluploadFile> files);

  public void onError(PluploadError error);

  // I'd like to enable this but the behavior seems inconsistent right now. I
  // have a hack workaround implemented in the connector but we should revisit
  // pending the outcome of http://dev.vaadin.com/ticket/10946.
  // @Delayed(lastOnly = true)
  public void onUploadProgress(PluploadFile file);

  public void onFileUploaded(PluploadFile file);

  public void onFilesRemoved(List<PluploadFile> files);

  public void onInit(String runtime);

  public void onUploadComplete(List<PluploadFile> files);
}
