package org.mpilone.vaadin.shared;

import com.vaadin.shared.communication.ServerRpc;

/**
 * The remote procedure call interface which allows calls from the client side
 * to the server. For the most part these methods map to the events generated by
 * the Plupload JavaScript component.
 *
 * @author mpilone
 */
public interface PluploadServerRpc extends ServerRpc {
  void onUploadFile(PluploadFile file);

   void onError(PluploadError error);

  void onFileUploaded(PluploadFile file);

  void onInit(String runtime);

  void onProgress(int percent);

  void onStateChanged(int state);
}
